"""Test suite validating the dynamic Shields.io badge endpoints and how they are published.

The badge JSON is generated by the release workflow and published to the unprotected
`badges` branch, not committed to `main`: `main` requires the "Quality Gate" status check,
so a release run cannot push there and every attempt was rejected with
`GH006: Protected branch update failed`. These tests therefore validate the generator and
the links that point at it, rather than a committed copy that would only drift.
"""

import json
import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
RELEASE_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "build-and-release.yml"
README = REPO_ROOT / "README.md"

PUBLISHED_BRANCH = "badges"
EXPECTED_BADGES = {"image-size", "upstream-version", "flavors"}


def badge_generator_script() -> str:
    """Return the shell script of the release step that generates the badge endpoints."""
    workflow = yaml.safe_load(RELEASE_WORKFLOW.read_text(encoding="utf-8"))
    steps = workflow["jobs"]["check-and-release"]["steps"]
    publishing = [s for s in steps if s.get("name", "").startswith("Publish Badge Endpoints")]
    assert len(publishing) == 1, f"Expected exactly one badge-publishing step, found {len(publishing)}"
    return publishing[0]["run"]


def extract_badges(script: str) -> dict:
    """Parse each `cat <<EOF > $BADGES/<name>.json` heredoc into a JSON object.

    Shell interpolations are replaced with a placeholder so the body can be parsed; the
    point is to prove the generator emits well-formed Shields.io documents.
    """
    pattern = re.compile(
        r'cat <<EOF > "\$BADGES/(?P<name>[a-z-]+)\.json"\n(?P<body>.*?)\n\s*EOF',
        re.DOTALL,
    )
    badges = {}
    for match in pattern.finditer(script):
        body = re.sub(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}|\$[A-Za-z_][A-Za-z0-9_]*", "X", match.group("body"))
        badges[match.group("name")] = json.loads(body)
    return badges


class TestShieldsBadges:
    """Assertions ensuring the generated badge endpoints conform to the Shields.io schema."""

    def test_workflow_generates_every_expected_badge(self):
        """The release workflow must emit all three endpoint documents."""
        badges = extract_badges(badge_generator_script())
        assert set(badges) == EXPECTED_BADGES, (
            f"Generated badges {sorted(badges)} do not match expected {sorted(EXPECTED_BADGES)}"
        )
        assert len(badges) == 3

    def test_generated_badges_conform_to_shields_schema(self):
        """Every generated badge is valid JSON carrying the fields Shields.io requires."""
        badges = extract_badges(badge_generator_script())
        assert badges, "No badge documents could be parsed from the release workflow"

        for name, data in badges.items():
            assert data.get("schemaVersion") == 1, f"{name} must specify schemaVersion: 1"
            assert "label" in data, f"{name} missing 'label'"
            assert "message" in data, f"{name} missing 'message'"
            assert "color" in data, f"{name} missing 'color'"
            assert str(data["message"]).strip(), f"{name} message must not be empty"

    def test_flavors_badge_contains_all_hardware_targets(self):
        """The flavors badge lists all five published hardware flavors."""
        badges = extract_badges(badge_generator_script())
        message = badges["flavors"]["message"]
        for expected in ["all", "intel", "amd", "cuda", "cuda13"]:
            assert expected in message, f"Flavor '{expected}' missing from flavors badge: {message}"
        assert badges["flavors"]["label"] == "Hardware Flavors"

    def test_version_badge_is_sourced_from_the_extracted_upstream_version(self):
        """The version badge must carry the detected upstream version, never a literal.

        It is also guarded against the "latest" sentinel: publishing that would show a
        meaningless version on the README until the next successful extraction.
        """
        script = badge_generator_script()
        assert '"message": "$VERSION"' in script, "Version badge does not use the extracted version"
        assert 'if [ -n "$VERSION" ] && [ "$VERSION" != "latest" ]; then' in script, (
            "Version badge is not guarded against the 'latest' sentinel"
        )

    def test_badges_are_published_off_the_protected_branch(self):
        """Generated badges go to the unprotected branch, never committed to main.

        A push to `main` from the release run is rejected by branch protection, so a
        reintroduced commit there would silently leave every badge stale.
        """
        script = badge_generator_script()
        assert "push --quiet origin badges" in script, "Badges are not published to the badges branch"
        assert "HEAD:main" not in script, "Release step must not attempt to push to the protected branch"
        assert not (REPO_ROOT / "docs" / "badges").exists(), (
            "docs/badges/ is back in the tree; it would duplicate and drift from the published branch"
        )

    def test_readme_badges_point_at_the_published_branch(self):
        """Every README endpoint badge resolves to the branch the workflow actually writes."""
        endpoints = re.findall(r"https://img\.shields\.io/endpoint\?url=(\S+?)\)", README.read_text(encoding="utf-8"))
        assert len(endpoints) == len(EXPECTED_BADGES), (
            f"Expected {len(EXPECTED_BADGES)} endpoint badges in README, found {len(endpoints)}"
        )

        for url in endpoints:
            assert f"/{PUBLISHED_BRANCH}/" in url, f"Badge URL does not read from the '{PUBLISHED_BRANCH}' branch: {url}"
            assert "/main/docs/badges/" not in url, f"Badge URL still points at the stale in-tree copy: {url}"
            assert Path(url).stem in EXPECTED_BADGES, f"Unknown badge endpoint referenced: {url}"
